### ISSUE TITLE
Recording does not save/ continue when switching between Record/History/Post processing tab

### ISSUE THREAD

**Issue by jpapagia** [lukasbach/pensieve#4]
Hi Lukas, I love the project. One small bug I have ran into:
**Describe the bug**
While recording a meeting, if you switch to History/ Post processing tab, the current recording is immediately discarded without notice. All progress is gone, including notes that were taken along with the meeting.

**To Reproduce**
Start a new meeting, and while the meeting is recording, switch tabs, and then switch back to the recording tab.

**Expected behavior**
Meeting should continue to record when switching tabs to history or postprocessing log.

**Screenshots**
![image](https://github.com/lukasbach/pensieve/assets/171886243/53ead5bb-6ffa-40da-95ea-00ecaf5c297f)
![image](https://github.com/lukasbach/pensieve/assets/171886243/98413c24-1340-4b8b-b9ca-8a40057d804b)
![image](https://github.com/lukasbach/pensieve/assets/171886243/17621d6a-1242-4089-bba1-bb504441939a)

**Additional context**
- Windows 11 23H2
- 1.0.10

Best,
John

**Comment by lukasbach** [comment]
Hey @jpapagia, thanks for the report and the details! I'm sorry for the issue, I hope you didn't loose any important recording data from that. I've fixed the issue in the latest release 1.0.11, which should automatically download on the next restart. Please let me know if you still experience issues with the new version.

**Comment by jpapagia** [comment]
So far, so good. Thank and keep up the great work  :)
